window.DORI_QUIZ_FILES = [
  "A fák tetején/erdei fülesbagoly 1.jpg",
  "A fák tetején/meggyvágó 1.jpg",
  "A lomb közepén/kakukk 1.jpg",
  "A lomb közepén/kakukk 2.jpg",
  "A lomb közepén/nagy fakopáncs 1.jpg",
  "A lomb közepén/sárgarigó 1.jpg",
  "A lomb közepén/szajkó 1.jpg",
  "Árokpartok növényei/egérárpa 1.jpg",
  "Árokpartok növényei/egérárpa 2.jpg",
  "Árokpartok növényei/egérárpa 3.jpg",
  "Árokpartok növényei/fehérhere 1.jpg",
  "Árokpartok növényei/lándzás útifű 1.jpg",
  "Árokpartok növényei/lándzsás útifű 2.jpg",
  "Árokpartok növényei/magas és kanadai aranyvessző 1.jpg",
  "Árokpartok növényei/magas és kanadai aranyvessző 2.jpg",
  "Árokpartok növényei/magas és kanadai aranyvessző 3.jpg",
  "Árokpartok növényei/mezei cickafark 1.jpg",
  "Árokpartok növényei/mezei cickafark 2.jpg",
  "Árokpartok növényei/mezei cickafark 3.jpg",
  "Árokpartok növényei/mezei katáng 1.jpg",
  "Árokpartok növényei/mezei katáng 2.jpg",
  "Árokpartok növényei/pásztortáska 1.jpg",
  "Árokpartok növényei/pásztortáska 2.jpg",
  "Árokpartok növényei/piros árvacsalán 1.jpg",
  "Árokpartok növényei/piros árvacsalán 2.jpg",
  "Árokpartok növényei/repkényveronika 1.jpg",
  "Árokpartok növényei/réti útifű 1.jpg",
  "Árokpartok növényei/salátaboglárka 1.jpg",
  "Árokpartok növényei/salátaboglárka 2.jpg",
  "Árokpartok növényei/tyúkhúr 1.jpg",
  "Árokpartok növényei/tyúkhúr 2.jpg",
  "Árokpartok növényei/vérehulló fecskefű 1.jpg",
  "Árokpartok növényei/vérehulló fecskefű 2.jpg",
  "Árokpartok növényei/vöröshere 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/erdei pajzsika 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/erdei pajzsika 2.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/erdei pajzsika 3.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/erdei szőrmoha 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/gyöngyvirág 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/gyöngyvirág 2.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/kikeleti hóvirág (védett) 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/medvehagyma 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/medvehagyma 2.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/odvas keltike 1.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/odvas keltike 2.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/odvas keltike 3.jpg",
  "AZ ERDŐ ALJNÖVÉNYZETE/tőzike (védett) 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/bükk 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/bükk 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/bükk 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/bükk 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/bükk 5.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/cserjÉk 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/cserszömörce 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/cserszömörce 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/cserszömörce 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/cserszömörce 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csertölgy 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csertölgy 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csíkos kecskerágó 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csíkos kecskerágó 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csíkos kecskerágó 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/csíkos kecskerágó 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/egybibés galagonya 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/egybibés galagonya 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/egybibés galagonya 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/erdei fenyő 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/erdei fenyő 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/erdei fenyő 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/erdei fenyő 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fagyal 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fagyal 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fagyal 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fekete bodza 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fekete bodza 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fekete bodza 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/fekete bodza 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/húsos som 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/húsos som 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/húsos som 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kocsányos tölgy 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kocsányos tölgy 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kocsánytalan tölgy 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kökény 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kökény 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kökény 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kökény 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/kökény 5.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/korai juhar 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/korai juhar 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/korai juhar 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/korai juhar 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges boróka 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges boróka 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges boróka 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 5.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges gyertyán 6.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 5.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/közönséges mogyoró 6.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/lucfenyő 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/lucfenyő 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/lucfenyő 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/lucfenyő 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 5.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/magas kőris 6.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/nagylevelű hárs 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/nagylevelű hárs 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/nagylevelű hárs 3.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/nagylevelű hárs 4.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/vadkörte (vackor) 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/vadkörte (vackor) 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/vadrózsa (csipkerózsa, gyepűrózsa) 1.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/vadrózsa (csipkerózsa, gyepűrózsa) 2.jpg",
  "AZ ERDŐ ÉLŐVILÁGA/vadrózsa (csipkerózsa, gyepűrózsa) 3.jpg",
  "Bokrokban/erdei pinty 1.jpg",
  "EGYSZIKŰEK/angolperje 1.jpg",
  "EGYSZIKŰEK/angolperje 2.jpg",
  "EGYSZIKŰEK/angolperje 3.jpg",
  "EGYSZIKŰEK/Árvalányhaj 1.jpg",
  "EGYSZIKŰEK/Árvalányhaj 2.jpg",
  "EGYSZIKŰEK/Árvalányhaj 3.jpg",
  "Emlősök/barna medve 1.jpg",
  "Emlősök/borz 1.jpg",
  "Emlősök/dámvad 1.jpg",
  "Emlősök/dámvad 2.jpg",
  "Emlősök/erdei cickány 1.jpg",
  "Emlősök/erdei egér 1.jpg",
  "Emlősök/európai mókus 1.jpg",
  "Emlősök/európai őz 1.jpg",
  "Emlősök/európai őz 2.jpg",
  "Emlősök/európai őz 3.jpg",
  "Emlősök/gímszarvas 1.jpg",
  "Emlősök/gímszarvas 2.jpg",
  "Emlősök/hiúz 1.jpg",
  "Emlősök/keleti sün 1.jpg",
  "Emlősök/közönséges denevér 1.jpg",
  "EMLŐSÖK/közönséges ürge 1.jpg",
  "EMLŐSÖK/közönséges vakond 1.jpg",
  "EMLŐSÖK/mezei nyúl 1.jpg",
  "EMLŐSÖK/mezei pocok 1.jpg",
  "EMLŐSÖK/mezei pocok 2.jpg",
  "Emlősök/muflon 1.jpg",
  "Emlősök/nyuszt 1.jpg",
  "Emlősök/nyuszt 2.jpg",
  "Emlősök/szürke farkas 1.jpg",
  "Emlősök/vaddisznó 1.jpg",
  "Emlősök/vaddisznó 2.jpg",
  "Emlősök/vadmacska 1.jpg",
  "Emlősök/vörös róka 1.jpg",
  "Emlősök/vörös róka 2.jpg",
  "Gombák/erdei csiperke 1.jpg",
  "Gombák/erdei csiperke 2.jpg",
  "Gombák/gyilkos galóca 1.jpg",
  "Gombák/gyilkos galóca 2.jpg",
  "Gombák/légyölő galóca 1.jpg",
  "Gombák/nagy őzlábgomba 1.jpg",
  "Gombák/taplógomba 1.jpg",
  "HALAK/réti csík 1.jpg",
  "HALAK/réti csík 2.jpg",
  "Harasztok/mezei zsurló 1.jpg",
  "Harasztok/mezei zsurló 2.jpg",
  "Hüllők/erdei sikló 1.jpg",
  "Hüllők/erdei sikló 2.jpg",
  "HÜLLŐK/fürge gyík 1.jpg",
  "HÜLLŐK/fürge gyík 2.jpg",
  "Hüllők/keresztes vipera 1.jpg",
  "Hüllők/lábatlan gyík (törékeny gyík, kuszma) 1.jpg",
  "Hüllők/lábatlan gyík (törékeny gyík, kuszma) 2.jpg",
  "HÜLLŐK/rákosi vipera 1.jpg",
  "Ízeltlábúak/aranyos rózsabogár 1.jpg",
  "Ízeltlábúak/betűző szú 1.jpg",
  "Ízeltlábúak/betűző szú 2.jpg",
  "Ízeltlábúak/betűző szú 3.jpg",
  "Ízeltlábúak/burgonyabogár (krumplibogár) 1.jpg",
  "Ízeltlábúak/erdei vöröshangya 1.jpg",
  "Ízeltlábúak/erdei vöröshangya 2.jpg",
  "Ízeltlábúak/gyapjaslepke 1.jpg",
  "Ízeltlábúak/gyapjaslepke 2.jpg",
  "Ízeltlábúak/gyapjaslepke 3.jpg",
  "Ízeltlábúak/harlekin katica 1.jpg",
  "Ízeltlábúak/harlekin katica 2.jpg",
  "Ízeltlábúak/hétpettyes katicabogár 1.jpg",
  "Ízeltlábúak/hétpettyes katicabogár 2.jpg",
  "Ízeltlábúak/kék nünüke 1.jpg",
  "Ízeltlábúak/közönséges barna százlábú 1.jpg",
  "Ízeltlábúak/közönséges kullancs 1.jpg",
  "Ízeltlábúak/májusi cserebogár 1.jpg",
  "Ízeltlábúak/nagy ganajtúró 1.jpg",
  "Ízeltlábúak/nagy hőscincér 1.jpg",
  "Ízeltlábúak/nagy szarvasbogár 2.jpg",
  "Ízeltlábúak/nagy szarvasbogár hím 1.jpg",
  "Ízeltlábúak/nagy szentjánosbogár hím 1.jpg",
  "Ízeltlábúak/nagy szentjánosbogár nőstény 1.jpg",
  "Kétéltűek/barna varangy 1.jpg",
  "Kétéltűek/foltos szalamandra 1.jpg",
  "Kétéltűek/zöld levelibéka 1.jpg",
  "KÉTSZIKŰEK/apró nőszirom 1.jpg",
  "KÉTSZIKŰEK/cizfra kankalin 1.jpg",
  "KÉTSZIKŰEK/fehér mécsvirág 1.jpg",
  "KÉTSZIKŰEK/fehér mécsvirág 2.jpg",
  "KÉTSZIKŰEK/fekete kökörcsin 1.jpg",
  "KÉTSZIKŰEK/kövirózsa 1.jpg",
  "KÉTSZIKŰEK/leány kökörcsin 1.jpg",
  "KÉTSZIKŰEK/magyar nőszirom 1.jpg",
  "KÉTSZIKŰEK/mezei kakukkfű 1.jpg",
  "KÉTSZIKŰEK/mezei kakukkfű 2.jpg",
  "KÉTSZIKŰEK/mezei szarkaláb 1.jpg",
  "KÉTSZIKŰEK/mezei szarkaláb 2.jpg",
  "KÉTSZIKŰEK/mezei zsálya 1.jpg",
  "KÉTSZIKŰEK/mezei zsálya 2.jpg",
  "KÉTSZIKŰEK/orvosi székfű kamilla 1.jpg",
  "KÉTSZIKŰEK/orvosi székfű kamilla 2.jpg",
  "KÉTSZIKŰEK/Őszi kikerics 1.jpg",
  "KÉTSZIKŰEK/Őszi kikerics 2.jpg",
  "KÉTSZIKŰEK/Őszi kikerics 3.jpg",
  "KÉTSZIKŰEK/pipacs 1.jpg",
  "KÉTSZIKŰEK/pipacs 2.jpg",
  "KÉTSZIKŰEK/pipacs 3.jpg",
  "KÉTSZIKŰEK/pipacs 4.jpg",
  "KÉTSZIKŰEK/pipacs 5.jpg",
  "KÉTSZIKŰEK/pongyolapitypang gyermekláncfű 1.jpg",
  "KÉTSZIKŰEK/pongyolapitypang gyermekláncfű 2.jpg",
  "KÉTSZIKŰEK/selyemkóró 1.jpg",
  "KÉTSZIKŰEK/selyemkóró 2.jpg",
  "KÉTSZIKŰEK/selyemkóró 3.jpg",
  "KÉTSZIKŰEK/selyemkóró 4.jpg",
  "KÉTSZIKŰEK/szártalan kankalin 1.jpg",
  "KÉTSZIKŰEK/tavaszi hérics 1.jpg",
  "KÉTSZIKŰEK/tavaszi hérics 2.jpg",
  "KÉTSZIKŰEK/tavaszi kankalin 1.jpg",
  "KÉTSZIKŰEK/tövises iglice 1.jpg",
  "KÉTSZIKŰEK/tövises iglice 2.jpg",
  "KÉTSZIKŰEK/Ürömlevelű parlagfű 1.jpg",
  "KÉTSZIKŰEK/Ürömlevelű parlagfű 2.jpg",
  "KÉTSZIKŰEK/Ürömlevelű parlagfű 3.jpg",
  "KÉTSZIKŰEK/Útszéli bogáncs 1.jpg",
  "KÉTSZIKŰEK/Útszéli bogáncs 2.jpg",
  "KÉTSZIKŰEK/Útszéli bogáncs 3.jpg",
  "Környezetünk leggyakoribb/ázsiai márványos poloska 1.jpg",
  "Környezetünk leggyakoribb/Érdes pinceászka 1.jpg",
  "Környezetünk leggyakoribb/ezüstös ősrovar (pikkelyke) 1.jpg",
  "Környezetünk leggyakoribb/fürkészdarázs 1.jpg",
  "Környezetünk leggyakoribb/házi légy 1.jpg",
  "Környezetünk leggyakoribb/háziméh 1.jpg",
  "Környezetünk leggyakoribb/káposztalepke 1.jpg",
  "Környezetünk leggyakoribb/káposztalepke 2.jpg",
  "Környezetünk leggyakoribb/káposztalepke 3.jpg",
  "Környezetünk leggyakoribb/kaszáspók 1.jpg",
  "Környezetünk leggyakoribb/kék fadongó 1.jpg",
  "Környezetünk leggyakoribb/konyhai csótány 1.jpg",
  "Környezetünk leggyakoribb/koronás keresztespók 1.jpg",
  "Környezetünk leggyakoribb/közönséges fülbemászó 1.jpg",
  "Környezetünk leggyakoribb/légyölő pókszázlábú 1.jpg",
  "Környezetünk leggyakoribb/légyölő pókszázlábú 2.jpg",
  "Környezetünk leggyakoribb/lisztmoly 1.jpg",
  "Környezetünk leggyakoribb/lisztmoly 2.jpg",
  "Környezetünk leggyakoribb/német darázs 1.jpg",
  "Környezetünk leggyakoribb/poszméh 1.jpg",
  "Környezetünk leggyakoribb/ruhamoly 1.jpg",
  "Környezetünk leggyakoribb/ruhamoly 2.jpg",
  "Környezetünk leggyakoribb/verőköltő bodobács 1.jpg",
  "Környezetünk leggyakoribb/zöld vándorpoloska 1.jpg",
  "Környezetünk leggyakoribb/zöld vándorpoloska 2.jpg",
  "Környezetünk leggyakoribb/zöld vándorpoloska 3.jpg",
  "Madarak/dolmányos varjú 1.jpg",
  "Madarak/egerészölyv 1.jpg",
  "Madarak/egerészölyv 2.jpg",
  "Madarak/fácán 1.jpg",
  "Madarak/fácán 2.jpg",
  "Madarak/fehér gólya 1.jpg",
  "Madarak/mezei pacsirta 1.jpg",
  "Madarak/parlagi sas 1.jpg",
  "Madarak/szarka 1.jpg",
  "Madarak/túzok 1.jpg",
  "Madarak/túzok 2.jpg",
  "Madarak/vetési varjú 1.jpg",
  "Madáretetők leggyakoribb vendégei/csuszka 1.jpg",
  "Madáretetők leggyakoribb vendégei/feketerigó 1.jpg",
  "Madáretetők leggyakoribb vendégei/feketerigó 2.jpg",
  "Madáretetők leggyakoribb vendégei/fülemüle (csalogány) 1.jpg",
  "Madáretetők leggyakoribb vendégei/füstifecske 1.jpg",
  "Madáretetők leggyakoribb vendégei/füstifecske 2.jpg",
  "Madáretetők leggyakoribb vendégei/házi rozsdafarkú 1.jpg",
  "Madáretetők leggyakoribb vendégei/házi veréb 1.jpg",
  "Madáretetők leggyakoribb vendégei/házi veréb 2.jpg",
  "Madáretetők leggyakoribb vendégei/kék cinege 1.jpg",
  "Madáretetők leggyakoribb vendégei/molnárfecske 1.jpg",
  "Madáretetők leggyakoribb vendégei/molnárfecske 2.jpg",
  "Madáretetők leggyakoribb vendégei/partifecske 1.jpg",
  "Madáretetők leggyakoribb vendégei/partifecske 2.jpg",
  "Madáretetők leggyakoribb vendégei/széncinege 1.jpg",
  "Madáretetők leggyakoribb vendégei/tengelic 1.jpg",
  "Madáretetők leggyakoribb vendégei/vörösbegy 1.jpg",
  "Madáretetők leggyakoribb vendégei/zöldike 1.jpg",
  "Parkok leggyakoribb fái/bugás csörgőfa 1.jpg",
  "Parkok leggyakoribb fái/bugás csörgőfa 2.jpg",
  "Parkok leggyakoribb fái/bugás csörgőfa 3.jpg",
  "Parkok leggyakoribb fái/bugás csörgőfa 4.jpg",
  "Parkok leggyakoribb fái/juharlevelű platán 1.jpg",
  "Parkok leggyakoribb fái/juharlevelű platán 2.jpg",
  "Parkok leggyakoribb fái/juharlevelű platán 3.jpg",
  "Parkok leggyakoribb fái/közönséges nyír 1.jpg",
  "Parkok leggyakoribb fái/közönséges nyír 2.jpg",
  "Parkok leggyakoribb fái/közönséges nyír 3.jpg",
  "Parkok leggyakoribb fái/madárberkenye 1.jpg",
  "Parkok leggyakoribb fái/madárberkenye 2.jpg",
  "Parkok leggyakoribb fái/madárberkenye 3.jpg",
  "Parkok leggyakoribb fái/magyallevelű mahónia 1.jpg",
  "Parkok leggyakoribb fái/mezei szil 1.jpg",
  "Parkok leggyakoribb fái/mezei szil 2.jpg",
  "Parkok leggyakoribb fái/mezei szil 3.jpg",
  "Parkok leggyakoribb fái/mirigyes bálványfa 1.jpg",
  "Parkok leggyakoribb fái/mirigyes bálványfa 2.jpg",
  "Parkok leggyakoribb fái/mirigyes bálványfa 3.jpg",
  "Parkok leggyakoribb fái/mirigyes bálványfa 4.jpg",
  "Parkok leggyakoribb fái/szelídgesztenye 1.jpg",
  "Parkok leggyakoribb fái/szelídgesztenye 2.jpg",
  "Parkok leggyakoribb fái/szelídgesztenye 3.jpg",
  "Parkok leggyakoribb fái/szelídgesztenye 4.jpg",
  "Parkok leggyakoribb fái/tiszafa 1.jpg",
  "Parkok leggyakoribb fái/tiszafa 2.jpg",
  "Parkok leggyakoribb fái/tiszafa 3.jpg",
  "Parkok leggyakoribb fái/vadgesztenye (bokrétafa) 1.jpg",
  "Puhatestűek/spanyol meztelencsiga 1.jpg",
  "ROVAROK/Ájtatos manó (imádkozó sáska) 1.jpg",
  "ROVAROK/közönséges boglárkalepke 1.jpg",
  "ROVAROK/közönséges boglárkalepke 2.jpg",
  "ROVAROK/közönséges rétisáska 1.jpg",
  "ROVAROK/közönséges rétisáska 2.jpg",
  "ROVAROK/mezei tücsök 1.jpg",
  "ROVAROK/nappali pávaszem 1.jpg",
  "ROVAROK/nappali pávaszem 2.jpg",
  "ROVAROK/nappali pávaszem 3.jpg",
  "ROVAROK/zöld lombszöcske 1.jpg"
]
;
